config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'

  devise_for :users, controllers: { sessions: 'devise/sessions' }

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'splash#index', as: :unauthenticated_root
    end
  end

  resources :categories do
     resources :entries, only: [:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_entry.rb
class CategoriesEntry < ApplicationRecord
  belongs_to :category
  belongs_to :entry
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :categories_entries
  has_many :entries, through: :categories_entries

  validates :name, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :categories_entries
  has_many :categories, through: :categories_entries

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

  def authenticate_user!
    return if devise_controller? || (controller_name == 'splash' && action_name == 'index')

    super
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def new
    @category = Category.new
  end

  def index
    @categories = Category.all.order(created_at: :asc)
  end

  def show
    @category = Category.find(params[:id])
    @transactions = @category.transactions
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to authenticated_root_path, notice: 'Category created successfully.'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon_url)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = Category.find(params[:category_id])
    @entry = Entry.new
  end

  def index
    @category = Category.find(params[:category_id])
    @entries = @category.entries.order(created_at: :desc)
  end

  def create
    @entry = Entry.new(entry_params)
    @category = Category.find(params[:category_id])

    if @entry.save
      redirect_to category_entries_path(@category), notice: 'Entry created successfully.'
    else
      puts "Entry Errors: #{entry.errors.full_messages}"
      render :new
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/_add_category_navbar.html.erb
<div data-turbo-frame="navbar">
  <nav class="navbar navbar-expand-lg navbar-light background-color-primary">
    <div class="container-fluid d-flex justify-content-between align-items-center">

      <div class="d-flex align-items-center justify-content-between w-100">
        <a href='/'>
          <img src="https://img.icons8.com/sf-black/35/ffffff/back.png" alt="back"/>
        </a>
        <h1 class='text-uppercase text-white fs-4 fw-bold'>New Category</h1>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarNav" aria-controls="navbarNav">
          <img src="https://img.icons8.com/ios-filled/30/ffffff/menu--v1.png" alt="Menu Icon">
        </button>
      </div>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="navbarNav" aria-labelledby="navbarNavLabel">
        <div class="offcanvas-header background-color-primary">
          <h5 class="offcanvas-title" id="navbarNavLabel"></h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close">
          </button>
        </div>
        <div class="offcanvas-body background-color-primary">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="d-flex flex-column align-items-center nav-item mb-3">
                <img src="https://img.icons8.com/pastel-glyph/100/FFFFFF/person-male--v2.png" alt="person-male--v2"/>
                <span class='text-capitalize text-white'><%= current_user.name %></span>
              </li>

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/engineering.png" alt="engineering" />
                <%= link_to 'Account settings', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
              
              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/marker.png" alt="marker"/>
                <%= link_to 'Merchant finder', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios-filled/25/FFFFFF/gift.png" alt="gift"/>
                <%= link_to 'Claim promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/glyph-neue/25/FFFFFF/share-2--v1.png" alt="share-2--v1"/>
                <%= link_to 'Share promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-vitaliy-gorbachev-fill-vitaly-gorbachev/25/FFFFFF/external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev.png" alt="external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev"/>
                <%= link_to 'Dashboard', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-tanah-basah-detailed-outline-tanah-basah/25/FFFFFF/external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah.png" alt="external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah"/>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, 'data-turbo-method': :delete, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/categories/_category_form.html.erb
<div class="d-flex flex-column mx-2 categories-list">
  <%= form_with(model: @category, url: categories_path, method: :post) do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', required: true, placeholder: 'Food' %>
    </div>
    <div class="form-group">
      <%= form.label :icon_url %>
      <%= form.text_field :icon_url, class: 'form-control', required: true, placeholder: 'Url of the icon' %>
    </div>
    <div class="form-group fixed-bottom p-3 border background-color-secondary">
      <%= form.submit "Save", class: 'btn background-color-secondary text-light text-uppercase border w-100 p-3 fw-bold' %>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="background-light-dark">
  <%= render 'add_category_navbar' %>
  <%= render 'category_form' %>
</div>

app/views/dashboard/_categories_list.html.erb
<div class='d-flex flex-column categories-list mx-2'>
  <% @categories.each do |category| %>
    <%= link_to category_entries_path(category), class: 'text-decoration-none' do %>
      <div class='d-flex bg-light mt-3 p-2'>
        <div>
          <img width="60px" height="60px" src="<%= category.icon_url %>" />
        </div>

        <div class='mx-3 flex-grow-1'>
          <div class="d-flex justify-content-between">
            <p><%= category.name %></p>
            <%= render partial: 'category_entry_sum', locals: { category: category } %>
          </div>
          <span class='text-muted' style='font-size:12px;'><%= category.created_at.strftime('%d %b %Y') %></span>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/dashboard/_category_entry_sum.html.erb
<% entries = category.entries %>
<span class='fw-bold'>$<%= number_with_precision(entries.sum(:amount), precision: 2) %></span>

app/views/dashboard/_navbar.html.erb
<div data-turbo-frame="navbar">
  <nav class="navbar navbar-expand-lg navbar-light background-color-primary">
    <div class="container">

      <span class='text-uppercase text-white fs-4 flex-grow-1'>Categories</span>

      <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarNav" aria-controls="navbarNav">
        <img src="https://img.icons8.com/ios-filled/30/ffffff/menu--v1.png" alt="Menu Icon">
      </button>

      <div class="offcanvas offcanvas-start" tabindex="-1" id="navbarNav" aria-labelledby="navbarNavLabel">
        <div class="offcanvas-header background-color-primary">
          <h5 class="offcanvas-title" id="navbarNavLabel"></h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close">
          </button>
        </div>
        <div class="offcanvas-body background-color-primary">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="d-flex flex-column align-items-center nav-item mb-3">
                <img src="https://img.icons8.com/pastel-glyph/100/FFFFFF/person-male--v2.png" alt="person-male--v2"/>
                <span class='text-capitalize text-white'><%= current_user.name %></span>
              </li>

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/engineering.png" alt="engineering" />
                <%= link_to 'Account settings', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
              
              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/marker.png" alt="marker"/>
                <%= link_to 'Merchant finder', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios-filled/25/FFFFFF/gift.png" alt="gift"/>
                <%= link_to 'Claim promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/glyph-neue/25/FFFFFF/share-2--v1.png" alt="share-2--v1"/>
                <%= link_to 'Share promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-vitaliy-gorbachev-fill-vitaly-gorbachev/25/FFFFFF/external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev.png" alt="external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev"/>
                <%= link_to 'Dashboard', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-tanah-basah-detailed-outline-tanah-basah/25/FFFFFF/external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah.png" alt="external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah"/>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, 'data-turbo-method': :delete, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/dashboard/index.html.erb
<div class="background-light-dark">
  <%= render 'navbar' %>
  
  <%= render partial: 'dashboard/categories_list', locals: { categories: @categories } %>
  
  <div class="fixed-bottom p-3 border background-color-secondary">
    <%= link_to "Add Category", new_category_path, class: 'btn background-color-secondary text-light text-uppercase border w-100 p-3 fw-bold' %>
  </div>
</div>

app/views/entries/_category_info.html.erb
<div class='d-flex bg-light mt-3 p-2'>
  <% if @category %>
    <div>
      <img width="60px" height="60px" src="<%= @category.icon_url %>" />
    </div>

    <div class='mx-3 flex-grow-1'>
      <div class="d-flex justify-content-between">
        <p><%= @category.name %></p>
        <!-- in here -->
        <span class='fw-bold'>$<%= number_with_precision(@entries.sum(:amount), precision: 2) %></span>
      </div>
      <span class='text-muted' style='font-size:12px;'><%= @category.created_at.strftime('%d %b %Y') %></span>
    </div>
  <% else %>
    <p>No category information available.</p>
  <% end %>
</div>

app/views/entries/_transaction_form_navbar.html.erb
<div data-turbo-frame="navbar">
  <nav class="navbar navbar-expand-lg navbar-light background-color-primary">
    <div class="container-fluid d-flex justify-content-between align-items-center">

      <div class="d-flex align-items-center justify-content-between w-100">
        <%= link_to category_entries_path(@category) do %>
          <img src="https://img.icons8.com/sf-black/35/ffffff/back.png" alt="back"/>
        <% end %>
        <h1 class='text-uppercase text-white fs-4 fw-bold'>New Transaction</h1>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarNav" aria-controls="navbarNav">
          <img src="https://img.icons8.com/ios-filled/30/ffffff/menu--v1.png" alt="Menu Icon">
        </button>
      </div>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="navbarNav" aria-labelledby="navbarNavLabel">
        <div class="offcanvas-header background-color-primary">
          <h5 class="offcanvas-title" id="navbarNavLabel"></h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close">
          </button>
        </div>
        <div class="offcanvas-body background-color-primary">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="d-flex flex-column align-items-center nav-item mb-3">
                <img src="https://img.icons8.com/pastel-glyph/100/FFFFFF/person-male--v2.png" alt="person-male--v2"/>
                <span class='text-capitalize text-white'><%= current_user.name %></span>
              </li>

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/engineering.png" alt="engineering" />
                <%= link_to 'Account settings', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
              
              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/marker.png" alt="marker"/>
                <%= link_to 'Merchant finder', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios-filled/25/FFFFFF/gift.png" alt="gift"/>
                <%= link_to 'Claim promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/glyph-neue/25/FFFFFF/share-2--v1.png" alt="share-2--v1"/>
                <%= link_to 'Share promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-vitaliy-gorbachev-fill-vitaly-gorbachev/25/FFFFFF/external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev.png" alt="external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev"/>
                <%= link_to 'Dashboard', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-tanah-basah-detailed-outline-tanah-basah/25/FFFFFF/external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah.png" alt="external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah"/>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, 'data-turbo-method': :delete, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/entries/_transactions_list_navbar.html.erb
<div data-turbo-frame="navbar">
  <nav class="navbar navbar-expand-lg navbar-light background-color-primary">
    <div class="container-fluid d-flex justify-content-between align-items-center">

      <div class="d-flex align-items-center justify-content-between w-100">
        <a href='/'>
          <img src="https://img.icons8.com/sf-black/35/ffffff/back.png" alt="back"/>
        </a>
        <h1 class='text-uppercase text-white fs-4 fw-bold'>Transactions</h1>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarNav" aria-controls="navbarNav">
          <img src="https://img.icons8.com/ios-filled/30/ffffff/menu--v1.png" alt="Menu Icon">
        </button>
      </div>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="navbarNav" aria-labelledby="navbarNavLabel">
        <div class="offcanvas-header background-color-primary">
          <h5 class="offcanvas-title" id="navbarNavLabel"></h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close">
          </button>
        </div>
        <div class="offcanvas-body background-color-primary">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="d-flex flex-column align-items-center nav-item mb-3">
                <img src="https://img.icons8.com/pastel-glyph/100/FFFFFF/person-male--v2.png" alt="person-male--v2"/>
                <span class='text-capitalize text-white'><%= current_user.name %></span>
              </li>

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/engineering.png" alt="engineering" />
                <%= link_to 'Account settings', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
              
              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios/25/FFFFFF/marker.png" alt="marker"/>
                <%= link_to 'Merchant finder', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/ios-filled/25/FFFFFF/gift.png" alt="gift"/>
                <%= link_to 'Claim promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/glyph-neue/25/FFFFFF/share-2--v1.png" alt="share-2--v1"/>
                <%= link_to 'Share promo', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-vitaliy-gorbachev-fill-vitaly-gorbachev/25/FFFFFF/external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev.png" alt="external-dashboard-blogger-vitaliy-gorbachev-fill-vitaly-gorbachev"/>
                <%= link_to 'Dashboard', authenticated_root_path, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">

              <li class="d-flex align-items-center nav-item">
                <img src="https://img.icons8.com/external-tanah-basah-detailed-outline-tanah-basah/25/FFFFFF/external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah.png" alt="external-sign-out-user-interface-tanah-basah-detailed-outline-tanah-basah"/>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, 'data-turbo-method': :delete, class: 'nav-link text-white mx-3' %>
              </li>
              <hr class=" custom-border">
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/entries/index.html.erb
<div>
  <%= render 'transactions_list_navbar' %>
  <%= render 'category_info' %>

  <div>
    <% @entries.each do |entry| %>
      <div class="border my-3 mx-2 p-2">
        <div class='d-flex justify-content-between'>
          <p class='fw-bold'><%= entry.name %></p>
          <p>$<%= entry.amount %></p>
        </div>
        <p class="text-muted">Date: <%= entry.created_at.strftime('%d %b %Y') %></</p>
      </div>
    <% end %>
  </div>

  <div class="fixed-bottom p-3 border background-color-secondary">
    <%= link_to "Add a new transaction", new_category_entry_path(category_id: @category.id), class: 'btn background-color-secondary text-light text-uppercase border w-100 p-3 fw-bold' %>
  </div>
</div>

app/views/entries/new.html.erb
<%= render 'transaction_form_navbar', category: @category %>

<%= form_with(model: [@category, @entry], url: category_entries_path(@category), local: true, data: { turbo_action: "submit" }) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true, placeholder: 'Transaction Name' %>
  </div>
  
  <div class="mb-3">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control", min: 0, required: true, placeholder: 'Transaction Amount' %>
  </div>
  
  <div class="mb-3">
    <%= form.label "CATEGORIES", class: "form-label" %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |category_form| %>
      <div class="form-check">
        <%= category_form.check_box class: "form-check-input" %>
        <%= category_form.label class: "form-check-label" do %>
          <%= category_form.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  
  <div class="mb-3 fw-6">
    * if you can't find your category click this <%= link_to "Add Category", new_category_path %> to add it!
  </div>

  <%= form.submit "Save", class: "w-100 fixed-bottom p-3 border background-color-secondary text-white text-uppercase fw-bold fs-5" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Pocket -- BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link type="image/png" sizes="16x16" rel="icon" href="https://img.icons8.com/cotton/64/wallet--v1.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="d-flex flex-column justify-content-between" style="min-height: 100vh;">
  <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">
    <h1>One Pocket</h1>
  </div>
  
  <div class='d-flex flex-column mt-auto'>
    <button type="button" class="btn btn-primary text-uppercase mb-3 mx-3 py-3">
      <%= link_to 'log in', new_user_session_path, class: 'nav-link' %>
    </button>
    <button type="button" class="btn btn-light text-uppercase mb-3 mx-3 py-3">
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
    </button>
  </div>
</div>

app/views/transactions/new.html.erb
<%= render 'transaction_form_navbar' %>

<%= form_with(model: [@category, @transaction], url: category_transactions_path(@category)) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true, placeholder: 'Transaction Name' %>
  </div>
  
  <div class="mb-3">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control", min: 0, required: true, placeholder: 'Transaction Amount' %>
  </div>
  
  <div class="mb-3">
    <%= form.label "CATEGORIES", class: "form-label" %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |category_form| %>
      <div class="form-check">
        <%= category_form.check_box class: "form-check-input" %>
        <%= category_form.label class: "form-check-label" do %>
          <%= category_form.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  
  <div class="mb-3 fw-6">
    * if you can't find your category click this <%= link_to "Add Category", new_category_path %> to add it!
  </div>

  <%= form.submit "Save", class: "w-100 fixed-bottom p-3 border background-color-secondary text-white text-uppercase fw-bold fs-5" %>
<% end %>